<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KuhinjaProizvodaObjekatTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kuhinjaProizvodaObjekti = [
            ['kuhinja_proizvoda_id' => 1, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 2, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 3, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 4, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 5, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 6, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 69, 'objekat_id' => 1],
            ['kuhinja_proizvoda_id' => 7, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 8, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 9, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 10, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 11, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 14, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 1, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 16, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 17, 'objekat_id' => 2],
            ['kuhinja_proizvoda_id' => 18, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 19, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 20, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 21, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 22, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 8, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 23, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 24, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 25, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 26, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 70, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 27, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 17, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 69, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 28, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 29, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 30, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 31, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 32, 'objekat_id' => 4],
            ['kuhinja_proizvoda_id' => 33, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 2, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 1, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 11, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 34, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 35, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 3, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 36, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 37, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 9, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 39, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 6, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 40, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 41, 'objekat_id' => 5],
            ['kuhinja_proizvoda_id' => 42, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 43, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 44, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 45, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 46, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 25, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 9, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 39, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 47, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 8, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 48, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 49, 'objekat_id' => 3],
            ['kuhinja_proizvoda_id' => 50, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 10, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 51, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 8, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 52, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 53, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 54, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 55, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 14, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 9, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 16, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 56, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 57, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 58, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 17, 'objekat_id' => 6],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 10, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 11, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 1, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 59, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 60, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 25, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 61, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 39, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 49, 'objekat_id' => 7],
            ['kuhinja_proizvoda_id' => 13, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 55, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 11, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 1, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 59, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 25, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 50, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 21, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 56, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 58, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 5, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 6, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 17, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 62, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 29, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 31, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 30, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 63, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 28, 'objekat_id' => 8],
            ['kuhinja_proizvoda_id' => 64, 'objekat_id' => 11],
            ['kuhinja_proizvoda_id' => 68, 'objekat_id' => 10],
            ['kuhinja_proizvoda_id' => 23, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 24, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 8, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 55, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 20, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 13, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 14, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 15, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 47, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 9, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 10, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 65, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 1, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 49, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 29, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 31, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 30, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 66, 'objekat_id' => 9],
            ['kuhinja_proizvoda_id' => 67, 'objekat_id' => 9]
        ];

        DB::table('kuhinja_proizvod_objekat')->insert($kuhinjaProizvodaObjekti);
    }
}
