<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProizvodPrilogTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $proizvodiPrilozi = [
            [ 'proizvod_id' => 28, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 28, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 29, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 30, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 31, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 32, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 33, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 34, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 35, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 36, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 37, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 38, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 39, 'prilog_id' =>9, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>1, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>2, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>3, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>4, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>5, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>6, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>7, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>8, 'cena' => 0 ],
            [ 'proizvod_id' => 40, 'prilog_id' =>9, 'cena' => 0 ],
        ];

        DB::table('proizvod_prilog')->insert($proizvodiPrilozi);
    }
}
